#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_DEFAULT="$SCRIPT_DIR"
OUTPUT_DIR_DEFAULT="$SCRIPT_DIR"
COMMAND_NAME_DEFAULT="aar"
BIN_DIR_DEFAULT="$HOME/.local/bin"
GENERATED_MARKER="# Generated by install-aar.sh for AnyAutoRegister."

REPO_ROOT="$REPO_ROOT_DEFAULT"
OUTPUT_DIR="$OUTPUT_DIR_DEFAULT"
COMMAND_NAME="$COMMAND_NAME_DEFAULT"
BIN_DIR="$BIN_DIR_DEFAULT"
FORCE="0"
GENERATED_SOURCE=""
INSTALL_PATH=""

usage() {
  cat <<EOF2
Usage: $(basename "$0") [--repo-root <path>] [--output-dir <path>] [--command-name <name>] [--bin-dir <path>] [--force]

Generate the local controller script and install the global command for AnyAutoRegister.

Options:
  --repo-root <path>      Service repo path (default: $REPO_ROOT_DEFAULT)
  --output-dir <path>     Directory for the generated controller script (default: $OUTPUT_DIR_DEFAULT)
  --command-name <name>   Global command name (default: $COMMAND_NAME_DEFAULT)
  --bin-dir <path>        PATH directory for installation (default: $BIN_DIR_DEFAULT)
  --force                 Overwrite existing generated and installed files
  --help                  Show this help message
EOF2
}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '%s\n' "$*"
}

abs_path() {
  local input="$1"
  if [[ -d "$input" ]]; then
    (cd "$input" && pwd)
    return
  fi

  local dir
  local base
  dir="$(cd "$(dirname "$input")" && pwd)"
  base="$(basename "$input")"
  printf '%s/%s\n' "$dir" "$base"
}

command_in_path() {
  local dir="$1"
  case ":$PATH:" in
    *":$dir:"*) return 0 ;;
    *) return 1 ;;
  esac
}

parse_args() {
  while (($# > 0)); do
    case "$1" in
      --repo-root)
        shift
        (($# > 0)) || fail "--repo-root requires a value"
        REPO_ROOT="$1"
        ;;
      --output-dir)
        shift
        (($# > 0)) || fail "--output-dir requires a value"
        OUTPUT_DIR="$1"
        ;;
      --command-name)
        shift
        (($# > 0)) || fail "--command-name requires a value"
        COMMAND_NAME="$1"
        ;;
      --bin-dir)
        shift
        (($# > 0)) || fail "--bin-dir requires a value"
        BIN_DIR="$1"
        ;;
      --force)
        FORCE="1"
        ;;
      --help|-h)
        usage
        exit 0
        ;;
      *)
        fail "Unknown argument: $1"
        ;;
    esac
    shift
  done
}

validate_inputs() {
  [[ "$COMMAND_NAME" =~ ^[a-z0-9-]{3,8}$ ]] || fail "--command-name must match [a-z0-9-]{3,8}"
  REPO_ROOT="$(abs_path "$REPO_ROOT")"
  OUTPUT_DIR="$(abs_path "$OUTPUT_DIR")"
  BIN_DIR="$(abs_path "$BIN_DIR")"

  [[ -d "$REPO_ROOT" ]] || fail "Repo root not found: $REPO_ROOT"
  [[ -f "$REPO_ROOT/start_server.sh" ]] || fail "Missing start_server.sh in $REPO_ROOT"
  [[ -f "$REPO_ROOT/main.py" ]] || fail "Missing main.py in $REPO_ROOT"
  [[ -f "$REPO_ROOT/frontend/package.json" ]] || fail "Missing frontend/package.json in $REPO_ROOT/frontend"

  mkdir -p "$OUTPUT_DIR"
  mkdir -p "$BIN_DIR"

  if ! command_in_path "$BIN_DIR"; then
    fail "Bin dir is not in PATH: $BIN_DIR. Add 'export PATH=\"$BIN_DIR:\$PATH\"' to your shell profile and rerun."
  fi
}

write_generated_controller() {
  local launcher_path="$OUTPUT_DIR/$COMMAND_NAME"
  local repo_root_literal

  printf -v repo_root_literal '%q' "$REPO_ROOT"

  if [[ -e "$launcher_path" && "$FORCE" != "1" ]]; then
    if ! grep -Fq "$GENERATED_MARKER" "$launcher_path" 2>/dev/null; then
      # 兼容仓库里旧版已跟踪的 aar，首次切回“本地生成”时允许覆盖。
      if [[ "$launcher_path" != "$REPO_ROOT/$COMMAND_NAME" ]]; then
        fail "Generated controller already exists: $launcher_path (use --force to overwrite)"
      fi
    fi
  fi

  cat >"$launcher_path" <<'EOF2'
#!/usr/bin/env bash
set -euo pipefail

__GENERATED_MARKER__

resolve_script_dir() {
  local source="${BASH_SOURCE[0]}"
  while [[ -h "$source" ]]; do
    local dir
    dir="$(cd -P "$(dirname "$source")" && pwd)"
    source="$(readlink "$source")"
    if [[ "$source" != /* ]]; then
      source="$dir/$source"
    fi
  done
  cd -P "$(dirname "$source")" && pwd
}

SCRIPT_DIR="$(resolve_script_dir)"
DEFAULT_REPO_ROOT=__REPO_ROOT__
REPO_ROOT="${AAR_REPO_ROOT:-$DEFAULT_REPO_ROOT}"
START_SCRIPT="$REPO_ROOT/start_server.sh"
CONDA_ENV_NAME="${CONDA_ENV_NAME:-3.11}"
COMMAND_NAME="$(basename "$0")"

usage() {
  cat <<EOF3
Usage: ${COMMAND_NAME} [menu|status|start|stop|restart|logs|help]

Commands:
  menu      Interactive menu (default)
  status    Show service status panel
  start     Start backend and frontend in background
  stop      Stop backend and frontend
  restart   Restart backend and frontend in background
  logs      Tail service logs
  help      Show this help message

Env:
  AAR_REPO_ROOT   Override repository root
  CONDA_ENV_NAME  Override conda env name
EOF3
}

ensure_layout() {
  if [[ ! -x "$START_SCRIPT" ]]; then
    echo "Error: start_server.sh not found: $START_SCRIPT" >&2
    exit 1
  fi
}

run_action() {
  local action="$1"
  shift || true
  REPO_ROOT="$REPO_ROOT" CONDA_ENV_NAME="$CONDA_ENV_NAME" "$START_SCRIPT" "$action" "$@"
}

print_status_panel() {
  run_action status
}

pause_continue() {
  printf '\n按回车键继续...'
  read -r _
  echo
}

interactive_menu() {
  while true; do
    clear
    print_status_panel
    echo
    echo "请选择操作："
    echo
    echo "  1) 查看状态"
    echo "  2) 启动服务"
    echo "  3) 停止服务"
    echo "  4) 重启服务"
    echo "  5) 查看日志"
    echo "  0) 退出"
    echo
    printf "请输入选项 [0-5]: "
    read -r choice
    case "$choice" in
      1) print_status_panel; pause_continue ;;
      2) run_action start --no-tail; pause_continue ;;
      3) run_action stop; pause_continue ;;
      4) run_action restart --no-tail; pause_continue ;;
      5) run_action logs ;;
      0) exit 0 ;;
      *) echo "无效选项"; pause_continue ;;
    esac
  done
}

main() {
  ensure_layout
  case "${1:-menu}" in
    menu)
      interactive_menu
      ;;
    status)
      shift || true
      print_status_panel
      ;;
    start|restart)
      action="$1"
      shift || true
      run_action "$action" --no-tail "$@"
      ;;
    stop|logs)
      action="$1"
      shift || true
      run_action "$action" "$@"
      ;;
    help|--help|-h)
      usage
      ;;
    *)
      echo "Unknown command: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
EOF2

  python3 - <<'PY' "$launcher_path" "$GENERATED_MARKER" "$repo_root_literal"
from pathlib import Path
import sys

path = Path(sys.argv[1])
marker = sys.argv[2]
repo_root_literal = sys.argv[3]
text = path.read_text()
text = text.replace('__GENERATED_MARKER__', marker)
text = text.replace('__REPO_ROOT__', repo_root_literal)
path.write_text(text)
PY

  chmod +x "$launcher_path"
  GENERATED_SOURCE="$launcher_path"
}

validate_install_target() {
  INSTALL_PATH="$BIN_DIR/$COMMAND_NAME"

  if [[ "$GENERATED_SOURCE" == "$INSTALL_PATH" ]]; then
    return 0
  fi

  if [[ -e "$INSTALL_PATH" && "$FORCE" != "1" ]]; then
    if [[ -L "$INSTALL_PATH" ]]; then
      local current_target
      current_target="$(readlink "$INSTALL_PATH")"
      if [[ "$current_target" == "$GENERATED_SOURCE" ]]; then
        return 0
      fi
    fi
    fail "Installed command already exists: $INSTALL_PATH (use --force to overwrite)"
  fi
}

install_command() {
  validate_install_target

  if [[ "$GENERATED_SOURCE" == "$INSTALL_PATH" ]]; then
    chmod +x "$GENERATED_SOURCE"
  else
    ln -sfn "$GENERATED_SOURCE" "$INSTALL_PATH"
  fi

  command -v "$COMMAND_NAME" >/dev/null 2>&1 || fail "Installed command is not discoverable: $COMMAND_NAME"
  log "Generated controller: $GENERATED_SOURCE"
  log "Installed global command: $INSTALL_PATH"
  log "Try: $COMMAND_NAME status"
}

main() {
  parse_args "$@"
  validate_inputs
  write_generated_controller
  install_command
}

main "$@"
